version: "1.1"
stages:
  - stage:
      - api-test:
          alias: api-test
          version: "2.0"
          params:
            body:
              type: none
            method: GET
            url: www.baidu.com
