version: "1.1"
"on":
  push:
    branches:
      - master
      - develop
      - feature/*
cron: 0 55 10 * * ?
stages:
  - stage:
      - api-test:
          alias: api-test
          description: 执行单个接口测试。上层可以通过 pipeline.yml 编排一组接口测试的执行顺序。
          version: "2.0"
          params:
            body:
              type: none
            method: GET
            url: www.ejwlkfjelwfj.com
