version: "1.1"
cron: 0 0 21 * * ?
cron_compensator:
  enable: false
  latest_first: true
  stop_if_latter_executed: true
stages:
  - stage:
      - api-test:
          alias: api-test
          description: 执行单个接口测试。上层可以通过 pipeline.yml 编排一组接口测试的执行顺序。
          version: "2.0"
          params:
            body:
              type: none
            method: GET
            url: www.baidu.com
