version: "1.1"
stages:
  - stage:
      - k8sflink:
          alias: flink-label-test
          description: 创建 Flink Job 集群
          params:
            bigDataConf:
              args:
                - --input
                - /opt/flink/README.txt
              class: org.apache.flink.streaming.examples.wordcount.WordCount
              envs:
                - name: test
                  value: hello
              flinkConf:
                jobManagerResource:
                  cpu: 200m
                  memory: 1024Mi
                  replica: 1
                kind: FlinkJob
                parallelism: 1
                taskManagerResource:
                  cpu: 200m
                  memory: 1024Mi
                  replica: 2
              image: registry.cn-hangzhou.aliyuncs.com/terminus/pyflink:1.12.0
              properties:
                taskManagerResource.numberOfTaskSlots: "1"
                taskmanager.memory.flink.size: 1024m
              resource: /opt/flink/examples/streaming/WordCount.jar
