version: "1.1"
stages:
  - stage:
      - git-checkout:
          alias: git-checkout
          description: 代码仓库克隆
  - stage:
      - golang:
          alias: go-demo
          description: golang action
          params:
            command: go build -o web-server main.go
            context: ${git-checkout}
            service: web-server
            target: web-server
