version: "1.1"
stages:
  - stage:
      - git-checkout:
          alias: git-checkout
          description: 代码仓库克隆
  - stage:
      - java-build:
          alias: java-build
          version: "1.0"
          params:
            build_cmd:
              - ls -l & chmod +x build.sh & ./build.sh
            jdk_version: "11"
            workdir: ${git-checkout}
