version: "1.1"
stages:
  - stage:
      - custom-script:
          alias: custom-script
          version: "1.0"
          commands:
            - sleep 3600
          resources:
            cpu: 0.1
            mem: 256
