openapi: 3.0.0

info:
  description: |
    # API 设计中心创建的 API 文档。
  
    请在『API 概况』中填写 API 文档的基本信息；在『API列表』新增接口描述；在『数据类型』中定义要引用的数据结构。
  title: dfef
  version: default
  
paths:
  /project:
    post:
      operationId: go-web-project
      requestBody:
        content:
          application/json:
            schema:
              example:
                propertyName1: Example
              properties:
                propertyName1:
                  example: Example
                  type: string
                  x-dice-name: propertyName1
                  x-dice-required: true
              required:
              - propertyName1
              type: object
              x-dice-media: application/json
          application/x-www-form-urlencoded:
            schema:
              example:
                a: Example
                b: Example
              properties:
                a:
                  example: Example
                  type: string
                  x-dice-name: a
                  x-dice-required: true
                b:
                  example: Example
                  type: string
                  x-dice-name: b
                  x-dice-required: true
              required:
              - a
              - b
              type: object
              x-dice-media: application/x-www-form-urlencoded
      responses:
        "200":
          content:
            application/json:
              schema:
                example: {}
                type: object
                x-dice-media: application/json
                x-dice-name: schema
          description: ""
      summary: go-web-project
      tags:
      - go-web-project
  
components:
  {}
  
tags:
  - name: other
  - name: go-web-project
  